const data = [
   
  { "id": 1, "question": "Define the macro environment.", "answer": "The macro environment refers to external factors that affect a business and are beyond its control, such as political, economic, social, technological, legal and environmental factors." },
  { "id": 2, "question": "List any three components of the macro environment.", "answer": "Political, Economic and Technological factors." },
  { "id": 3, "question": "Explain how economic factors affect businesses.", "answer": "Economic factors influence consumer spending, inflation, interest rates and business profitability." },
  { "id": 4, "question": "What is the market environment?", "answer": "The market environment consists of competitors, suppliers, customers and intermediaries that directly affect a business." },
  { "id": 5, "question": "Name two types of competitors.", "answer": "Direct competitors and indirect competitors." },
  { "id": 6, "question": "Define the micro environment.", "answer": "The micro environment includes internal factors within the business such as employees, management and resources." },
  { "id": 7, "question": "State one difference between micro and macro environments.", "answer": "The micro environment can be controlled, while the macro environment cannot be controlled." },
  { "id": 8, "question": "What is a SWOT analysis?", "answer": "A SWOT analysis identifies strengths, weaknesses, opportunities and threats of a business." },
  { "id": 9, "question": "Identify one internal factor in a SWOT analysis.", "answer": "Strengths." },
  { "id": 10, "question": "Explain why businesses conduct a SWOT analysis.", "answer": "To evaluate internal and external factors and develop effective strategies." },

  { "id": 11, "question": "Name the three main business sectors.", "answer": "Primary, Secondary and Tertiary sectors." },
  { "id": 12, "question": "Define the primary sector.", "answer": "The primary sector extracts raw materials from natural resources." },
  { "id": 13, "question": "Give one example of a primary sector business.", "answer": "Mining." },
  { "id": 14, "question": "Define the secondary sector.", "answer": "The secondary sector converts raw materials into finished or semi-finished products." },
  { "id": 15, "question": "Give one example of a secondary sector activity.", "answer": "Manufacturing." },
  { "id": 16, "question": "Define the tertiary sector.", "answer": "The tertiary sector provides services to consumers and businesses." },
  { "id": 17, "question": "Give one example of a tertiary sector business.", "answer": "Banking." },
  { "id": 18, "question": "State one importance of the tertiary sector.", "answer": "It provides essential services and supports other sectors." },
  { "id": 19, "question": "Which sector adds value to raw materials?", "answer": "The secondary sector." },
  { "id": 20, "question": "Which sector focuses on service delivery?", "answer": "The tertiary sector." },

  { "id": 21, "question": "Define entrepreneurship.", "answer": "Entrepreneurship is the process of starting and managing a business while taking financial risks." },
  { "id": 22, "question": "Name two characteristics of a successful entrepreneur.", "answer": "Creativity and risk-taking." },
  { "id": 23, "question": "What is a business plan?", "answer": "A written document outlining business goals and how they will be achieved." },
  { "id": 24, "question": "State one purpose of a business plan.", "answer": "To attract investors or obtain funding." },
  { "id": 25, "question": "Define capital.", "answer": "Capital refers to money or assets used to start or operate a business." },
  { "id": 26, "question": "Distinguish between fixed and working capital.", "answer": "Fixed capital is used to buy long-term assets, while working capital is used for daily operations." },
  { "id": 27, "question": "Define insurance.", "answer": "Insurance is a contract that protects a business against financial loss." },
  { "id": 28, "question": "State one principle of insurance.", "answer": "Utmost good faith." },
  { "id": 29, "question": "What is compulsory insurance?", "answer": "Insurance required by law, such as UIF contributions." },
  { "id": 30, "question": "Explain the importance of insurance to businesses.", "answer": "It reduces financial risk and provides compensation for losses." },

  { "id": 31, "question": "Define corporate social responsibility (CSR).", "answer": "CSR refers to businesses acting responsibly towards society and the environment." },
  { "id": 32, "question": "Give one example of CSR.", "answer": "Community development projects." },
  { "id": 33, "question": "What is professional conduct?", "answer": "Ethical and responsible behaviour in the workplace." },
  { "id": 34, "question": "State one example of unethical behaviour.", "answer": "Fraud." },
  { "id": 35, "question": "Define teamwork.", "answer": "Teamwork is people working together to achieve a common goal." },
  { "id": 36, "question": "Give one benefit of teamwork.", "answer": "Improved productivity." },
  { "id": 37, "question": "What is workplace diversity?", "answer": "Differences among employees such as culture, gender and age." },
  { "id": 38, "question": "State one advantage of workplace diversity.", "answer": "Increased creativity and innovation." },
  { "id": 39, "question": "Define workplace conflict.", "answer": "Disagreement or tension between employees." },
  { "id": 40, "question": "Give one method of resolving conflict.", "answer": "Mediation." },

  { "id": 41, "question": "Define quality management.", "answer": "Quality management ensures that products and services meet required standards." },
  { "id": 42, "question": "Name one quality indicator in production.", "answer": "Quality control." },
  { "id": 43, "question": "What is Total Quality Management (TQM)?", "answer": "A continuous improvement approach involving all employees." },
  { "id": 44, "question": "Define productivity.", "answer": "Productivity measures output in relation to input." },
  { "id": 45, "question": "State one way to improve productivity.", "answer": "Training employees." },
  { "id": 46, "question": "What is inventory management?", "answer": "Managing stock levels efficiently." },
  { "id": 47, "question": "Give one reason for holding stock.", "answer": "To meet customer demand." },
  { "id": 48, "question": "Define the purchasing function.", "answer": "The process of acquiring quality resources at the right price and time." },
  { "id": 49, "question": "What is human resource management?", "answer": "Managing employees within an organisation." },
  { "id": 50, "question": "State one function of human resource management.", "answer": "Recruitment." },

  { "id": 51, "question": "What is the purpose of labour legislation?", "answer": "To protect the rights of employees and employers." },
  { "id": 52, "question": "Name one labour law in South Africa.", "answer": "Basic Conditions of Employment Act." },
  { "id": 53, "question": "What is the Consumer Protection Act?", "answer": "Legislation that protects consumer rights." },
  { "id": 54, "question": "State one consumer right.", "answer": "The right to fair value." },
  { "id": 55, "question": "Define the Employment Equity Act.", "answer": "Legislation that promotes equal opportunities and fair treatment at work." },

  { "id": 56, "question": "What is a business strategy?", "answer": "A plan of action to achieve business objectives." },
  { "id": 57, "question": "Name one intensive strategy.", "answer": "Market penetration." },
  { "id": 58, "question": "Define diversification.", "answer": "Introducing new products into new markets." },
  { "id": 59, "question": "What is retrenchment?", "answer": "Termination of employment due to operational requirements." },
  { "id": 60, "question": "State one reason for retrenchment.", "answer": "Financial losses." },

  { "id": 61, "question": "Define leadership.", "answer": "The ability to influence others to achieve goals." },
  { "id": 62, "question": "Name one leadership style.", "answer": "Democratic leadership." },
  { "id": 63, "question": "What is management?", "answer": "The process of planning, organising, leading and controlling resources." },
  { "id": 64, "question": "State one management function.", "answer": "Planning." },
  { "id": 65, "question": "Define motivation.", "answer": "Encouraging employees to perform at their best." },

  { "id": 66, "question": "Define profit.", "answer": "Income remaining after expenses have been deducted." },
  { "id": 67, "question": "What is turnover?", "answer": "Total sales generated by a business." },
  { "id": 68, "question": "Define sustainability.", "answer": "Meeting present needs without compromising future generations." },
  { "id": 69, "question": "Define globalisation.", "answer": "The integration of economies across the world." },
  { "id": 70, "question": "State one benefit of globalisation.", "answer": "Access to international markets." },

  { "id": 71, "question": "Define business ethics.", "answer": "Moral principles guiding business behaviour." },
  { "id": 72, "question": "Give one example of ethical behaviour.", "answer": "Honest advertising." },
  { "id": 73, "question": "What is corporate governance?", "answer": "The system by which businesses are directed and controlled." },
  { "id": 74, "question": "State one principle of good corporate governance.", "answer": "Accountability." },
  { "id": 75, "question": "Why are ethics important in business?", "answer": "They build trust and protect the business reputation." },

  { "id": 76, "question": "Define innovation.", "answer": "Introducing new ideas, products or methods." },
  { "id": 77, "question": "What is creativity?", "answer": "The ability to generate new ideas." },
  { "id": 78, "question": "State one cause of workplace conflict.", "answer": "Poor communication." },
  { "id": 79, "question": "What is time management?", "answer": "The effective use of time to achieve goals." },
  { "id": 80, "question": "Give one benefit of time management.", "answer": "Increased efficiency." },

  { "id": 81, "question": "What is outsourcing?", "answer": "Using external service providers to perform business functions." },
  { "id": 82, "question": "Define a franchise.", "answer": "The right to operate a business using another company’s brand." },
  { "id": 83, "question": "What is a sole trader?", "answer": "A business owned and managed by one person." },
  { "id": 84, "question": "State one disadvantage of a sole trader.", "answer": "Unlimited liability." },
  { "id": 85, "question": "Define a partnership.", "answer": "A business owned by two or more people." },
  { "id": 86, "question": "What is a private company?", "answer": "A company with limited shareholders and restricted share transfer." },
  { "id": 87, "question": "Define a public company.", "answer": "A company that sells shares to the public." },
  { "id": 88, "question": "What is liquidity?", "answer": "The ability of a business to pay short-term debts." },
  { "id": 89, "question": "Define assets.", "answer": "Items owned by a business that have value." },
  { "id": 90, "question": "What are liabilities?", "answer": "Debts owed by a business." },

  { "id": 91, "question": "Define cash flow.", "answer": "The movement of money into and out of a business." },
  { "id": 92, "question": "What is the break-even point?", "answer": "The level where income equals expenses." },
  { "id": 93, "question": "Define market share.", "answer": "The portion of total market sales controlled by a business." },
  { "id": 94, "question": "What is customer satisfaction?", "answer": "Meeting or exceeding customer expectations." },
  { "id": 95, "question": "Define branding.", "answer": "Creating a unique identity for a product or business." },
  { "id": 96, "question": "What is advertising?", "answer": "Promoting products or services to customers." },
  { "id": 97, "question": "Define communication.", "answer": "The exchange of information between people." },
  { "id": 98, "question": "What is delegation?", "answer": "Assigning tasks and responsibilities to others." },
  { "id": 99, "question": "Define risk.", "answer": "The possibility of loss or damage." },
  { "id": 100, "question": "What is decision-making?", "answer": "Choosing the best option from available alternatives." }
];

export default data